--- #YAML:1.0
name: Gtk2Fu
version: 0.10
author: dams <dams@gentoo.org>
abstract: |-
  GTK2 Forked Ultimate, a powerful layer on top of Gtk2. (forked from ugtk2.)
license: perl
requires:
  Test::More: 0
provides:
  Gtk2::Box:
    file: lib/Gtk2Fu.pm
    version: 0.10
  Gtk2::Widget:
    file: lib/Gtk2Fu.pm
    version: 0.10
  Gtk2::Window:
    file: lib/Gtk2Fu.pm
    version: 0.10
  Gtk2::WrappedLabel:
    file: lib/Gtk2Fu.pm
    version: 0.10
  Gtk2Fu:
    file: lib/Gtk2Fu.pm
    version: 0.10
generated_by: Module::Build version 0.25
